// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    number_tile: 0,
    width_tile: 0,
    height_tile: 0,
    height_tile_name: 0,
    initialize: function() {
      this.setBind();
      return this.increaseHeigtTile();
    },
    setBind: function() {
      return $('#choki').bind('click', (function(_this) {
        return function() {};
      })(this));
    },
    showHeightNumber: function() {
      this.number_tile = _.random(0, 9);
      return $("#number" + this.height_tile_name).html(this.number_tile);
    },
    increaseHeigtTile: function() {
      var i, j, ref, results;
      this.height_tile = 10;
      this.height_tile_name = 0;
      results = [];
      for (i = j = 0, ref = this.height_tile; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.height_tile_name += 1;
        $('#height_tile').append("<div id=\"number" + this.height_tile_name + "\"></div>");
        results.push(this.showHeightNumber());
      }
      return results;
    }
  };

}).call(this);
