// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    width_tile: 0,
    height_tile: 0,
    width_tile_name: 0,
    height_tile_name: 0,
    theme_number: 0,
    sum_number: 0,
    point: 0,
    initial_count: 0,
    count: 0,
    click_count: 0,
    timer: false,
    click_number: 0,
    next_stage_number: 0,
    round: 0,
    initialize: function() {
      this.choiceParameter();
      this.increaseHeightTile();
      this.hideElement();
      return this.setBind();
    },
    choiceParameter: function() {
      this.width_tile = 5;
      this.height_tile = 5;
      this.click_count = this.width_tile * this.height_tile;
      this.sum_number = 0;
      return this.next_stage_number = 20;
    },
    increaseWidthTile: function(selecter) {
      var i, j, number_tile, ref, results;
      results = [];
      for (i = j = 0, ref = this.width_tile; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.width_tile_name += 1;
        number_tile = _.random(1, 9);
        $(selecter).append("<td id=\"width" + this.width_tile_name + "\" class= \"play_number\" data-number=\"" + number_tile + "\"></td>");
        $(selecter).data('number', 'number_tile');
        results.push($("#width" + this.width_tile_name).html(number_tile));
      }
      return results;
    },
    increaseHeightTile: function() {
      var i, j, ref, results;
      results = [];
      for (i = j = 0, ref = this.height_tile; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.height_tile_name += 1;
        $('#tile_area').append("<tr id=\"height" + this.height_tile_name + "\"></tr>");
        results.push(this.increaseWidthTile("#height" + this.height_tile_name));
      }
      return results;
    },
    hideElement: function() {
      this.hideSelecter('.before_game');
      return $('#start').html("<img src=\"./image/start.png\">");
    },
    hideSelecter: function(selecter) {
      return $(selecter).css({
        'display': 'none'
      });
    },
    showSelecter: function(selecter) {
      return $(selecter).css({
        'display': 'block'
      });
    },
    showThemeNumber: function() {
      this.stopCountTime();
      this.click_number = 0;
      this.sum_number = 0;
      this.theme_number = _.random(1, 19);
      return $('#theme_number_area').html(this.theme_number);
    },
    setBind: function() {
      var self;
      self = this;
      $('#start').bind('click', function() {
        return self.startGame();
      });
      $('.play_number').bind('click', function() {
        return self.choiceNumber(this);
      });
      return $('#reset').bind('click', function() {
        return self.changeStage();
      });
    },
    startGame: function() {
      this.round = 1;
      $('#round').html(this.round);
      this.point = 50;
      $('#point').html(this.point);
      this.hideSelecter('#start');
      this.showSelecter('.before_game');
      $('#round').css({
        'display': 'inline'
      });
      this.showThemeNumber();
      this.initial_count = 10;
      this.count = this.initial_count;
      return this.startCountTime();
    },
    choiceNumber: function(selecter) {
      var choice_number;
      if ($(selecter).hasClass('unusable')) {
        $(selecter).removeClass('unusable');
        this.sum_number -= choice_number;
        return $(selecter).css({
          'background-color': 'white'
        });
      } else {
        choice_number = $(selecter).data('number');
        this.click_count -= 1;
        this.sum_number = this.sum_number + choice_number;
        this.click_number += 1;
        $(selecter).addClass('unusable');
        $(selecter).css({
          'background-color': 'gray'
        });
        return this.calculationResult();
      }
    },
    calculationResult: function() {
      if (this.sum_number === this.theme_number) {
        this.showSelecter('#answer_area');
        $('#answer_area').removeClass('wrong_answer');
        $('#answer_area').addClass('correct_answer');
        $('#answer_area').html("good");
        this.disableTile('.unusable');
        $('.unusable').css({
          'pointer-events': 'none'
        });
        this.point += this.click_number * 10;
        $('#point').html(this.point);
        this.showThemeNumber();
        this.count = this.initial_count;
        this.startCountTime();
        this.showGameResult(this.round, 3, "Excellent");
        if (this.click_count <= this.next_stage_number) {
          this.round += 1;
          return this.changeStage();
        }
      } else if (this.sum_number > this.theme_number) {
        this.showSelecter('#answer_area');
        $('#answer_area').removeClass('correct_answer');
        $('#answer_area').addClass('wrong_answer');
        $('#answer_area').html("bad");
        this.disableTile('.unusable');
        $('.unusable').css({
          'pointer-events': 'none'
        });
        this.point -= 10;
        $('#point').html(this.point);
        this.showThemeNumber();
        this.count = this.initial_count;
        this.startCountTime();
        this.showGameResult(this.point, 0, "GameOver");
        if (this.click_count <= this.next_stage_number) {
          this.round += 1;
          return this.changeStage();
        }
      }
    },
    disableTile: function(selecter) {
      $(selecter).css({
        'background-color': 'black'
      });
      return $(selecter).css({
        'pointer-events': 'none'
      });
    },
    startCountTime: function() {
      var self;
      self = this;
      $('#count').html(self.count);
      return this.timer = setTimeout(function() {
        self.count -= 1;
        if (self.count === 0) {
          $('#count').html(self.count);
          self.showSelecter('.to_next_game');
          return self.showGameResult(self.count, 0, "GameOver");
        } else {
          return self.startCountTime();
        }
      }, 1000);
    },
    stopCountTime: function() {
      return clearTimeout(this.timer);
    },
    showGameResult: function(selecter, number, result) {
      if (selecter === number) {
        this.stopCountTime();
        this.disableTile('.play_number');
        this.showSelecter('#reset');
        this.showSelecter('#game_result');
        $('#game_result').html(result);
        return $('#reset').html("<img src=\"./image/reset.png\">");
      }
    },
    changeStage: function() {
      $('.play_number').removeClass('unusable');
      $('#tile_area').empty();
      this.hideSelecter('#reset');
      this.hideSelecter('#game_result');
      $('#reset').unbind('click');
      if (this.count === 0 || this.point === 0) {
        this.resetStage();
      }
      if (this.round > 1) {
        return this.changeNextStage();
      }
    },
    resetStage: function() {
      this.choiceParameter();
      this.round = 1;
      this.startGame();
      this.hideSelecter('.to_next_game');
      $('.play_number').css({
        'pointer-events': 'auto'
      });
      this.increaseHeightTile();
      return this.setBind();
    },
    changeNextStage: function() {
      this.choiceParameter();
      this.height_tile += 1;
      this.width_tile += 1;
      this.initial_count -= 1;
      this.count = this.initial_count;
      $('.play_number').css({
        'pointer-events': 'auto'
      });
      this.increaseHeightTile();
      this.showThemeNumber();
      this.startCountTime();
      this.setBind();
      return $('#round').html(this.round);
    }
  };

}).call(this);
