// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    number_tile: 0,
    width_tile: 0,
    height_tile: 0,
    width_tile_name: 0,
    height_tile_name: 0,
    theme_number: 0,
    sum_number: 0,
    choice_number: 0,
    point: 0,
    count: 0,
    click_count: 0,
    timer: false,
    click_number: 0,
    next_stage_number: 0,
    round: 0,
    initialize: function() {
      this.width_tile = 5;
      this.height_tile = 5;
      this.round = 0;
      this.point = 50;
      this.increaseHeightTile();
      this.choiceParameter();
      this.hideElement();
      this.setBind();
      return this.showPoint();
    },
    hideSelecter: function(selecter) {
      return $(selecter).css({
        'display': 'none'
      });
    },
    showSelecter: function(selecter) {
      return $(selecter).css({
        'display': 'block'
      });
    },
    hideElement: function() {
      $('#start').html("<img src=\"./image/start.png\">");
      this.hideSelecter('#tile_area');
      this.hideSelecter('#round');
      this.hideSelecter('#count_area');
      this.hideSelecter('#theme_number');
      this.hideSelecter('#answer_area');
      this.hideSelecter('#point_area');
      this.hideSelecter('#point');
      this.hideSelecter('#game_result');
      return this.hideSelecter('#reset');
    },
    choiceParameter: function() {
      this.round += 1;
      $('#round').html(this.round);
      this.click_count = this.width_tile * this.height_tile;
      this.sum_number = 0;
      return this.next_stage_number = 20;
    },
    showPoint: function() {
      return $('#point').html(this.point);
    },
    showThemeNumber: function() {
      this.stopCountTime();
      this.count = 10;
      this.click_number = 0;
      this.sum_number = 0;
      this.theme_number = _.random(1, 19);
      this.startCountTime();
      return $('#theme_number_area').html(this.theme_number);
    },
    increaseWidthTile: function(selecter) {
      var i, j, number_tile, ref, results;
      results = [];
      for (i = j = 0, ref = this.width_tile; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.width_tile_name += 1;
        number_tile = _.random(1, 9);
        $(selecter).append("<td id=\"width" + this.width_tile_name + "\" class= \"play_number\" data-number=\"" + number_tile + "\"></td>");
        $(selecter).data('number', 'number_tile');
        results.push($("#width" + this.width_tile_name).html(number_tile));
      }
      return results;
    },
    increaseHeightTile: function() {
      var i, j, ref, results;
      results = [];
      for (i = j = 0, ref = this.height_tile; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.height_tile_name += 1;
        $('#tile_area').append("<tr id=\"height" + this.height_tile_name + "\"></tr>");
        results.push(this.increaseWidthTile("#height" + this.height_tile_name));
      }
      return results;
    },
    setBind: function() {
      var self;
      self = this;
      $('#start').bind('click', function() {
        return self.startGame();
      });
      $('.play_number').bind('click', function() {
        return self.choiceNumber(this);
      });
      return $('#reset').bind('click', function() {
        return self.changeNextGame();
      });
    },
    startGame: function() {
      this.hideSelecter('#start');
      this.showSelecter('#round');
      this.showSelecter('#tile_area');
      this.showSelecter('#count_area');
      this.showSelecter('#theme_number');
      this.showSelecter('#answer_area');
      this.showSelecter('#point_area');
      this.showSelecter('#point');
      this.showSelecter('#game_result');
      return this.showThemeNumber();
    },
    choiceNumber: function(selecter) {
      if ($(selecter).hasClass('unusable')) {
        $(selecter).removeClass('unusable');
        this.choice_number = $(selecter).data('number');
        this.sum_number -= this.choice_number;
        return $(selecter).css({
          'background-color': 'white'
        });
      } else {
        this.choice_number = $(selecter).data('number');
        this.click_count -= 1;
        this.sum_number = this.sum_number + this.choice_number;
        this.click_number += 1;
        $(selecter).addClass('unusable');
        return this.calculationResult(selecter);
      }
    },
    calculationResult: function(selecter) {
      if (this.sum_number === this.theme_number) {
        $('#answer_area').addClass('correct_answer');
        $('#answer_area').html("good");
        this.disableTile('.unusable');
        this.point += this.click_number * 10;
        this.showPoint();
        this.showThemeNumber();
        if (this.click_count <= this.next_stage_number) {
          return this.changeNextGame();
        }
      } else if (this.sum_number > this.theme_number) {
        $('#answer_area').addClass('wrong_answer');
        $('#answer_area').html("bad");
        this.disableTile('.unusable');
        this.point -= 10;
        this.showPoint();
        this.showThemeNumber();
        this.showGameResult(this.point);
        if (this.click_count <= this.next_stage_number) {
          return this.changeNextGame();
        }
      } else {
        return $(selecter).css({
          'background-color': 'gray'
        });
      }
    },
    disableTile: function(selecter) {
      $(selecter).css({
        'background-color': 'black'
      });
      return $(selecter).css({
        'pointer-events': 'none'
      });
    },
    startCountTime: function() {
      var self;
      self = this;
      $('#count').html(self.count);
      return this.timer = setTimeout(function() {
        self.count -= 1;
        if (self.count === 0) {
          $('#count').html(self.count);
          self.disableTile('.unusable');
          return self.showGameResult(self.count);
        } else {
          return self.startCountTime();
        }
      }, 1000);
    },
    stopCountTime: function() {
      return clearTimeout(this.timer);
    },
    showGameResult: function(selecter) {
      if (selecter === 0) {
        this.stopCountTime();
        this.disableTile('.play_number');
        this.showSelecter('#reset');
        this.showSelecter('#game_result');
        $('#game_result').html("GameOver");
        return $('#reset').html("<img src=\"./image/reset.png\">");
      }
    },
    changeNextGame: function() {
      $('.play_number').removeClass('unusable');
      $('#tile_area').empty();
      $('.play_number').html('');
      this.height_tile += 1;
      this.width_tile += 1;
      this.choiceParameter();
      this.inputNumber();
      this.increaseHeightTile();
      $('.play_number').css({
        'background-color': 'white'
      });
      $('.play_number').css({
        'pointer-events': 'auto'
      });
      this.showThemeNumber();
      this.hideSelecter('#reset');
      this.hideSelecter('#game_result');
      return this.setBind();
    },
    inputNumber: function() {
      var i, j, number_tile, ref, results;
      this.width_tile_name = 0;
      console.log(this.click_count);
      results = [];
      for (i = j = 0, ref = this.click_count; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.width_tile_name += 1;
        number_tile = _.random(1, 9);
        $("#width" + this.width_tile_name).html(number_tile);
        results.push($("#width" + this.width_tile_name).data('number', number_tile));
      }
      return results;
    }
  };

}).call(this);
